base:
  random_stage: 10

data:
#loading data
  dataset_id: 891  # ID del dataset en el repositorio UCI
  save_processed_data: true  # Indica si deseas guardar los datos procesados
  processed_data_path: data/processed/cdc_diabetes_health_indicators.csv  # Ruta para guardar los datos procesados

train: 
#training, hyperparams
train_size: 0.8 


reports: 
#metrics, images, etc


  metrics:
    - accuracy
    - recall
    - gmean
    - precision
    - f1_score
    - confusion_matrix
  save_reports: true  # Indica si deseas guardar los reportes generados
  report_path: reports/  # Directorio donde se guardarán los reportes
  save_format: ['csv', 'png']  # Formatos en los que deseas guardar los reportes (opcional)
  confusion_matrix:
    display_labels: ['True Negatives', 'False Positives', 'False Negatives', 'True Positives']
    colormap: 'Spectral'
    figsize: [6, 4]
