stages:
  data_load:
    cmd: python src/stages/data_load.py --config=params.yaml
    deps:
    - src/stages/data_load.py
    params:
    - base
    - data
    outs:
    - data/raw/diabetes.csv

  featurize:
    cmd: python src/stages/featurize.py --config=params.yaml
    deps:
    - data/raw/diabetes.csv
    - src/stages/featurize.py
    params:
    - base
    - data
    - featurize
    outs:
    - data/processed/featured_diabetes.csv

  data_split:
    cmd: python src/stages/data_split.py --config=params.yaml
    deps:
    - data/processed/featured_diabetes.csv
    - src/stages/data_split.py
    params:
    - base
    - data_split
    - featurize
    outs:
    - data/processed/train_diabetes.csv
    - data/processed/train_target_diabetes.csv
    - data/processed/test_diabetes.csv
    - data/processed/test_target_diabetes.csv

  train:
    cmd: python src/stages/train.py --config=params.yaml
    deps:
    - data/processed/train_diabetes.csv
    - data/processed/train_target_diabetes.csv
    - src/stages/train.py
    params:
    - base
    - data_split.trainset_path
    - data_split.train_target
    - train
    outs:
    - models/model.joblib

  evaluate:
    cmd: python src/stages/evaluate.py --config=params.yaml
    deps:
    - data/processed/test_diabetes.csv
    - data/processed/test_target_diabetes.csv
    - models/model.joblib
    - src/stages/evaluate.py
    params:
    - base
    - data_split.testset_path
    - data_split.test_target
    - evaluate
    plots:
    - reports/confusion_matrix_data.csv:
        template: confusion
        x: predicted
        y: y_true
        cache: false
    metrics:
    - reports/metrics.json:
        cache: false
