base:
  random_state: 42
  log_level: INFO

data:
  dataset_csv: 'data/raw/diabetes.csv'

featurize:
  features_path: 'data/processed/featured_diabetes.csv'
  target_column: Diabetes_binary

data_split:
  test_size: 0.8
  trainset_path: 'data/processed/train_diabetes.csv'
  train_target: 'data/processed/train_target_diabetes.csv'
  testset_path: 'data/processed/test_diabetes.csv'
  test_target: 'data/processed/test_target_diabetes.csv'


train:
  logistic_regression:
    max_iter: 1000
  random_forest:
    n_estimators: 100
    max_depth: 10
  model_path: models/model.joblib


evaluate:
  reports_dir: reports
  metrics_file: 'metrics.json'
  confusion_matrix_image: 'confusion_matrix.png'