base:
  seed: 42

data_load:
  dataset_csv: 'data/raw/iris.csv'

data_split:
  test_size: 0.2
  trainset_path: 'data/processed/train_iris.csv'
  testset_path: 'data/processed/test_iris.csv'

train:
  cv: 3
  estimator_name: logreg
  C: 0.001
  max_iter: 100
  solver: 'lbfgs'
  multi_class: 'multinomial'
  model_path: models/model.joblib
